include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - avoid_print: false
    - prefer_const_constructors: true
    - prefer_const_declarations: true
    - use_key_in_widget_constructors: false
    - avoid_unnecessary_containers: true
    - sized_box_for_whitespace: true
    - use_super_parameters: true
